import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <script src="https://kit.fontawesome.com/46fc7c2460.js" crossorigin="anonymous"></script>
        {/* Other meta tags, title, and links */}
      </Head>
      <body className={inter.className}>
      <div className="flex">
      <Sidebar  />
      <div className="flex-grow">{children}</div>
    </div>
      </body>
    </html>
  );
}
